### ISSUE TITLE
[BLOG] BTCpay logo left corner messes with design Safari

### ISSUE THREAD

**Issue by Conimous** [btcpayserver/btcpayserver.org#85] opened 2020-03-25 15:33 UTC
Hey there, 

Just was looking at the Blog.btcpayserver.org and found that the B from the logo obstructs quiet a bit see attachment. Went from main site to Blog.

Cheers.

![Schermafbeelding 2020-03-25 om 16 29 33](https://user-images.githubusercontent.com/41842951/77554316-33c6ef00-6eb6-11ea-8641-479d88b79eb1.png)

**Comment by Eskyee** [comment] 2020-04-25 08:39
@dennisreimann I think the problem is the lazy loading " lazyload class"  
preloading and not to preloaded lazy bug stuff, happens in safari !!

@pavlenex  

 this does not happen in Firefox or chrome, just apple, so far I found.

![IMG_2560](https://user-images.githubusercontent.com/30862925/80275285-2a5cbc80-86d8-11ea-9b35-4f0402648d97.jpg)
![IMG_2561](https://user-images.githubusercontent.com/30862925/80275289-2fba0700-86d8-11ea-8ad5-7082cb9de60e.jpg)

![IMG_2562](https://user-images.githubusercontent.com/30862925/80275294-39dc0580-86d8-11ea-80a2-c91eecd03bfa.jpg)

![IMG_2565](https://user-images.githubusercontent.com/30862925/80275297-3f395000-86d8-11ea-9d1e-ec43a60793cd.jpg)


bug is in pixels being shown ,  by lazyload bug,  should be just 50 x 50 , no size change on logo.

**Comment by Eskyee** [comment] 2020-04-25 08:40
then we can close this issue :)

**Comment by dennisreimann** [comment] 2020-04-26 10:24
I can reproduce it in Safari. 

To fix it, we'd need to change this CSS rule

```css
.wp-custom-logo .title-area img {
  width: auto;
}
```

… and apply the width of 50 pixels:

```css
.wp-custom-logo .title-area img {
  width: 50px;
}
```

Do we have the source for the blog on GitHub too? Haven't found a repo.

**Comment by pavlenex** [comment] 2020-04-26 10:37
Ok, check now @Eskyee

**Comment by Eskyee** [comment] 2020-04-26 10:38
Sorted 🙌

**Comment by Eskyee** [comment] 2020-04-26 10:39
No problems now with size on logo.

**Closed as completed** 2020-04-26 10:41 UTC

**Comment by Eskyee** [comment] 2020-04-26 10:43
<img width="1440" alt="Screenshot 2020-04-26 at 11 41 08" src="https://user-images.githubusercontent.com/30862925/80305135-f0141d80-87b2-11ea-968b-bf9a2a496528.png">

just need to sort out the boxes now, as it looks untidy, middle box shorter,  cheers guys

**Comment by dennisreimann** [comment] 2020-04-26 10:52
yep, fixed 👍

**Comment by Eskyee** [comment] 2020-04-26 18:42
<img width="1440" alt="Screenshot 2020-04-26 at 19 41 40" src="https://user-images.githubusercontent.com/30862925/80316465-02fc1180-87f6-11ea-96b9-0f203c7555b5.png">

Perfect ❤️
